# Loki Observability Stack
# Deploys: Prometheus/Grafana + Loki + Promtail + OTEL + MinIO + Argo Workflows + K6
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stack-loki
  namespace: argocd
  labels:
    layer: stack
    stack: loki
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Metrics - Prometheus/Grafana
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/components/observability/prometheus-stack
      directory:
        recurse: false
        include: 'kube-prometheus-stack.yaml'

    # Logs - Loki
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/components/observability/loki
      directory:
        recurse: false
        include: 'loki.yaml'

    # Logs - Promtail (log shipper for Loki)
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/components/observability/promtail
      directory:
        recurse: false
        include: 'promtail.yaml'

    # Traces - OpenTelemetry
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/components/observability/otel-collector
      directory:
        recurse: false
        include: 'otel-collector.yaml'

    # Storage - MinIO (S3-compatible for Loki)
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/components/storage/minio
      directory:
        recurse: false
        include: 'minio.yaml'

    # Workflows - Argo Workflows
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/components/workflows/argo-workflows
      directory:
        recurse: false
        include: 'argo-workflows.yaml'

    # Load Testing - K6
    - repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
      targetRevision: HEAD
      path: argocd-apps/components/workflows/k6
      directory:
        recurse: false
        include: 'k6-operator.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
